### ISSUE TITLE
How do i use this package with react

### ISSUE THREAD

**Issue by Qhristen** [concord-consortium/drawing-tool#26]

**Comment by sfentress** [comment]
Hi @Qhristen , there is no deep integration with React at the moment. However, you can create a component that renders a div, and then render the drawing tool into it either using a hook or in `componentDidMount`.

We have an example of doing it with a hook here: https://github.com/concord-consortium/question-interactives/blob/master/src/drawing-tool/components/drawing-tool.tsx

(There's a lot of other stuff going on in this component, but the relevant parts are creating the new drawing tool with `new DrawingToolLib("#drawing-tool-container", drawingToolOpts);` and then calling `load` on that object, which we do in a hook).

**Comment by Qhristen** [comment]
Thanks for the response @sfentress
